# Site settings
title: Jeremy Reyes
email: im@jeremyreyes.com
description: > # this means to ignore newlines until "baseurl:"
  Jeremy Reyes
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jeremyreyes.com" # the base hostname & protocol for your site
twitter_username: djreyes
github_username:  djreyes

# Build settings
markdown: kramdown
